import LayoutProvider from '@/components/LayoutProvider'
import './globals.css'
import type { Metadata } from 'next'

import './../stylesheets/commonClasses.css'
import './../stylesheets/antdOverride.css'
import './../stylesheets/layout.css'
import './../stylesheets/loader.css'
import './../stylesheets/jobs.css'

import ReduxProvider from '@/components/ReduxProvider'

export const metadata: Metadata = {
  title: 'Ocisti',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReduxProvider>
      <LayoutProvider>{children}</LayoutProvider>
    </ReduxProvider>
  )
}
